### ISSUE TITLE
Feature Request: Faster Assigning

### ISSUE THREAD

**Issue by GameDevon** [p4535992/foundryvtt-farchievements#1]
Could there be an option to assign an achievement to a player by right clicking it in the gm view? Like it would give you a little dropdown menu about who you're giving it to. At the moment you have to go into the edit menu which I would like to see made more intuitive. I really like this module so far and I am excited to see its development.

**Comment by p4535992** [comment]
This is not the officialy repository for this module go here https://github.com/Handyfon/Farchievements/issues
