### ISSUE TITLE
[BUG] Unable to perform anything

### ISSUE THREAD

**Issue by deakmark** [p4535992/foundryvtt-farchievements#2]
I created an achievement which become blank and I was unable to edit it. After that I become unable to perform any modification within the module.
The error what I see in console:
VM219882:579  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
    at <anonymous>:579:52
    at Array.filter (<anonymous>)
    at setAchievement (<anonymous>:579:38)
(anonymous) @ VM219882:579
setAchievement @ VM219882:579
await in setAchievement (async)
onclick @ game:1

**Comment by p4535992** [comment]
This is not the officialy repository for this module go here https://github.com/Handyfon/Farchievements/issues
